### ISSUE TITLE
[QUESTION] Can I use fake original files?

### ISSUE THREAD

**Issue by RetroGameTalk** [SonicMastr/rePatch-reLoaded#7]
Do I need to keep the original encrypted file on my NoNpDrm dump? if it's gonna get replaced by repatch anyway, can't I have an empty 0 bytes file named for example "data.psarc"?

**Comment by Yoti** [comment]
Yes, you can safely remove original (app/NoNpDrm) files via replacing them with empty file + rePatch one.

**Comment by RetroGameTalk** [comment]
Thanks I found I can straight up delete the original files. Repatch will use the ones from repatch.

**Comment by Yoti** [comment]
> Thanks I found I can straight up delete the original files.

Some games will break then.
